/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as MyHoursRouteImport } from './routes/my-hours'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupervisorLoginRouteImport } from './routes/supervisor.login'
import { Route as SupervisorFormsRouteImport } from './routes/supervisor.forms'
import { Route as FormsNewRouteImport } from './routes/forms.new'
import { Route as CleanupNewRouteImport } from './routes/cleanup.new'
import { Route as ApiPublicMarkhamCleanupChatRouteImport } from './routes/api.public.markham-cleanup-chat'

const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHoursRoute = MyHoursRouteImport.update({
  id: '/my-hours',
  path: '/my-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorLoginRoute = SupervisorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorFormsRoute = SupervisorFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => SupervisorRoute,
} as any)
const FormsNewRoute = FormsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FormsRoute,
} as any)
const CleanupNewRoute = CleanupNewRouteImport.update({
  id: '/cleanup/new',
  path: '/cleanup/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarkhamCleanupChatRoute =
  ApiPublicMarkhamCleanupChatRouteImport.update({
    id: '/api/public/markham-cleanup-chat',
    path: '/api/public/markham-cleanup-chat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forms': typeof FormsRouteWithChildren
  '/my-hours': typeof MyHoursRoute
  '/supervisor': typeof SupervisorRouteWithChildren
  '/cleanup/new': typeof CleanupNewRoute
  '/forms/new': typeof FormsNewRoute
  '/supervisor/forms': typeof SupervisorFormsRoute
  '/supervisor/login': typeof SupervisorLoginRoute
  '/api/public/markham-cleanup-chat': typeof ApiPublicMarkhamCleanupChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forms': typeof FormsRouteWithChildren
  '/my-hours': typeof MyHoursRoute
  '/supervisor': typeof SupervisorRouteWithChildren
  '/cleanup/new': typeof CleanupNewRoute
  '/forms/new': typeof FormsNewRoute
  '/supervisor/forms': typeof SupervisorFormsRoute
  '/supervisor/login': typeof SupervisorLoginRoute
  '/api/public/markham-cleanup-chat': typeof ApiPublicMarkhamCleanupChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forms': typeof FormsRouteWithChildren
  '/my-hours': typeof MyHoursRoute
  '/supervisor': typeof SupervisorRouteWithChildren
  '/cleanup/new': typeof CleanupNewRoute
  '/forms/new': typeof FormsNewRoute
  '/supervisor/forms': typeof SupervisorFormsRoute
  '/supervisor/login': typeof SupervisorLoginRoute
  '/api/public/markham-cleanup-chat': typeof ApiPublicMarkhamCleanupChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forms'
    | '/my-hours'
    | '/supervisor'
    | '/cleanup/new'
    | '/forms/new'
    | '/supervisor/forms'
    | '/supervisor/login'
    | '/api/public/markham-cleanup-chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forms'
    | '/my-hours'
    | '/supervisor'
    | '/cleanup/new'
    | '/forms/new'
    | '/supervisor/forms'
    | '/supervisor/login'
    | '/api/public/markham-cleanup-chat'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forms'
    | '/my-hours'
    | '/supervisor'
    | '/cleanup/new'
    | '/forms/new'
    | '/supervisor/forms'
    | '/supervisor/login'
    | '/api/public/markham-cleanup-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FormsRoute: typeof FormsRouteWithChildren
  MyHoursRoute: typeof MyHoursRoute
  SupervisorRoute: typeof SupervisorRouteWithChildren
  CleanupNewRoute: typeof CleanupNewRoute
  ApiPublicMarkhamCleanupChatRoute: typeof ApiPublicMarkhamCleanupChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-hours': {
      id: '/my-hours'
      path: '/my-hours'
      fullPath: '/my-hours'
      preLoaderRoute: typeof MyHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/login': {
      id: '/supervisor/login'
      path: '/login'
      fullPath: '/supervisor/login'
      preLoaderRoute: typeof SupervisorLoginRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/forms': {
      id: '/supervisor/forms'
      path: '/forms'
      fullPath: '/supervisor/forms'
      preLoaderRoute: typeof SupervisorFormsRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/forms/new': {
      id: '/forms/new'
      path: '/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof FormsNewRouteImport
      parentRoute: typeof FormsRoute
    }
    '/cleanup/new': {
      id: '/cleanup/new'
      path: '/cleanup/new'
      fullPath: '/cleanup/new'
      preLoaderRoute: typeof CleanupNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/markham-cleanup-chat': {
      id: '/api/public/markham-cleanup-chat'
      path: '/api/public/markham-cleanup-chat'
      fullPath: '/api/public/markham-cleanup-chat'
      preLoaderRoute: typeof ApiPublicMarkhamCleanupChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FormsRouteChildren {
  FormsNewRoute: typeof FormsNewRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsNewRoute: FormsNewRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

interface SupervisorRouteChildren {
  SupervisorFormsRoute: typeof SupervisorFormsRoute
  SupervisorLoginRoute: typeof SupervisorLoginRoute
}

const SupervisorRouteChildren: SupervisorRouteChildren = {
  SupervisorFormsRoute: SupervisorFormsRoute,
  SupervisorLoginRoute: SupervisorLoginRoute,
}

const SupervisorRouteWithChildren = SupervisorRoute._addFileChildren(
  SupervisorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  FormsRoute: FormsRouteWithChildren,
  MyHoursRoute: MyHoursRoute,
  SupervisorRoute: SupervisorRouteWithChildren,
  CleanupNewRoute: CleanupNewRoute,
  ApiPublicMarkhamCleanupChatRoute: ApiPublicMarkhamCleanupChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
