/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as MyHoursRouteImport } from './routes/my-hours'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CleanupNewRouteImport } from './routes/cleanup.new'

const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHoursRoute = MyHoursRouteImport.update({
  id: '/my-hours',
  path: '/my-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanupNewRoute = CleanupNewRouteImport.update({
  id: '/cleanup/new',
  path: '/cleanup/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/my-hours': typeof MyHoursRoute
  '/supervisor': typeof SupervisorRoute
  '/cleanup/new': typeof CleanupNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/my-hours': typeof MyHoursRoute
  '/supervisor': typeof SupervisorRoute
  '/cleanup/new': typeof CleanupNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/my-hours': typeof MyHoursRoute
  '/supervisor': typeof SupervisorRoute
  '/cleanup/new': typeof CleanupNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/my-hours'
    | '/supervisor'
    | '/cleanup/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/my-hours'
    | '/supervisor'
    | '/cleanup/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/my-hours'
    | '/supervisor'
    | '/cleanup/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MyHoursRoute: typeof MyHoursRoute
  SupervisorRoute: typeof SupervisorRoute
  CleanupNewRoute: typeof CleanupNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-hours': {
      id: '/my-hours'
      path: '/my-hours'
      fullPath: '/my-hours'
      preLoaderRoute: typeof MyHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanup/new': {
      id: '/cleanup/new'
      path: '/cleanup/new'
      fullPath: '/cleanup/new'
      preLoaderRoute: typeof CleanupNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MyHoursRoute: MyHoursRoute,
  SupervisorRoute: SupervisorRoute,
  CleanupNewRoute: CleanupNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
